"""add notebook_cells table

Revision ID: 1f5b28ea04d6
Revises: 72b0553cdb24
Create Date: 2026-09-16 13:29:43.031657

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1f5b28ea04d6"
down_revision: str | None = "72b0553cdb24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notebook_cells",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "cell_type",
            sa.Enum("MARKDOWN", "CODE", name="celltype", native_enum=False),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("execution_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "ERROR", name="cellstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notebook_cells_session_id"), "notebook_cells", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notebook_cells_session_id"), table_name="notebook_cells")
    op.drop_table("notebook_cells")
    # ### end Alembic commands ###
