"""create sessions table

Revision ID: 72b0553cdb24
Revises:
Create Date: 2026-09-16 12:13:27.451873

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "72b0553cdb24"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "CSV",
                "TSV",
                "EXCEL",
                "JSON",
                "JSON_LINES",
                "PARQUET",
                name="filetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "NEEDS_SHEET_SELECTION",
                "PROFILING",
                "READY",
                "ERROR",
                name="sessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sheet_names", sa.JSON(), nullable=True),
        sa.Column("selected_sheet", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("profile", sa.JSON(), nullable=True),
        sa.Column("preview_rows", sa.JSON(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
